version: 2.1

executors:
  default:
    working_directory: ~/repo/atomic-flyway

    docker:
      - image: cimg/base:stable
        environment:
          JVM_OPTS: -Xmx4096m
          TERM: dumb

commands:
  install-jdk:
    description: Install and setup the JDK environmnet
    parameters:
      major:
        description: The JDK major version to use
        type: string
        default: "19"
      version:
        description: The JDK full version to use
        type: string
        default: "19.0.1"

    steps:
      - run:
          name: Get JDK SHA256
          command: |
            mkdir ~/jdk
            wget "https://download.oracle.com/java/<<parameters.major>>/archive/jdk-<<parameters.version>>_linux-x64_bin.tar.gz.sha256" -O ~/jdk/jdk-<<parameters.major>>.sha256

      - restore_cache:
          key: v1-<<parameters.major>>-{{ checksum "~/jdk/jdk-<<parameters.major>>.sha256" }}

      - run:
          name: Download JDK
          command: |
            if [ ! -f ~/jdk/jdk-<<parameters.major>>.tar.gz ]; then
              wget -nc https://download.oracle.com/java/<<parameters.major>>/archive/jdk-<<parameters.version>>_linux-x64_bin.tar.gz -O ~/jdk/jdk-<<parameters.major>>.tar.gz
            fi

      - run:
          name: Install JDK
          command: |
            sudo tar xvf ~/jdk/jdk-<<parameters.major>>.tar.gz -C ~/jdk/
            sudo mkdir /opt/jdk-<<parameters.major>>
            sudo mv ~/jdk/jdk-<<parameters.major>>*/* /opt/jdk-<<parameters.major>>
            echo 'export JAVA_HOME=/opt/jdk-<<parameters.major>>' >> $BASH_ENV
            echo 'export PATH=$PATH:$JAVA_HOME/bin' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Check Java version
          command: |
            echo $JAVA_HOME
            java --version

      - save_cache:
          paths:
            - ~/jdk/jdk-<<parameters.major>>.tar.gz
          key: v1-<<parameters.major>>-{{ checksum "~/jdk/jdk-<<parameters.major>>.sha256" }}

  setup:
    description: Setup the project environment

    steps:
      - checkout:
          path: ~/repo/atomic-flyway

      - restore_cache:
          keys:
            - v2-gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildscript-gradle.lockfile" }}-{{ checksum "gradle.lockfile" }}

      - run:
          name: Provisioning
          command: |
            sed -i "s/{SIGNING_PASSWORD}/$SIGNING_PASSWORD/g" gradle.properties
            sed -i "s/{NEXUS_USERNAME_TOKEN}/$NEXUS_USERNAME_TOKEN/g" gradle.properties
            sed -i "s/{NEXUS_PASSWORD_TOKEN}/$NEXUS_PASSWORD_TOKEN/g" gradle.properties

      - run:
          name: Dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/repo/atomic-flyway/.gradle
            - ~/.gradle
          key: v2-gradle-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildscript-gradle.lockfile" }}-{{ checksum "gradle.lockfile" }}

  install-nodejs:
    description: Install NodeJS and Yarn dependencies

    steps:
      - run:
          name: Install NodeJS
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --install' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install yarn
          command: npm install -g yarn

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install packages
          command: yarn install --immutable

      - save_cache:
          paths:
            - ~/repos/atomic-flyway/.yarn/cache
          key: yarn-v1-{{ checksum "yarn.lock" }}

jobs:
  build:
    executor: default

    steps:
      - install-jdk

      - setup

      - run:
          name: Compile
          command: ./gradlew compileJava compileTestJava

      - run:
          name: SonarLint
          command: ./gradlew sonarlintMain sonarlintTest

      - run:
          name: Checkstyle
          command: ./gradlew checkstyleMain checkstyleTest

      - run:
          name: Test
          command: ./gradlew test

      - run:
          name: Check Javadoc
          command: ./gradlew javadoc

      - run:
          name: Build
          command:  ./gradlew build

  publish:
    executor: default

    steps:
      - install-jdk

      - setup

      - install-nodejs

      - run:
          name: Publish to Maven Central
          command: yarn release

workflows:
  main:
    jobs:
      - build

      - publish:
          requires:
            - build
          filters:
            branches:
              only: release
